# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8e0dbefcdde9e669eca4fda9915879d4c293311d2edb4707a9dd24569bb4e665ce43f2dd33c3612b3dfffbcdf5d55223113d756080177f06ea1419cd7969a5

test:
  secret_key_base: f2acc5b0cd022d38e4a06b571e9bdba79d3a829ac9e0fa4956e290af52ce6546c27dc03b430c2d50dc92a9a83312c5c7f7b950186ad0406a8836d004515ff437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
